/*
 * DEMO CONTENT. Not client data. Rendered only when PUBLIC_DEMO=true.
 * Images in public/demo/ are procedurally generated by scripts/generate-demo-images.py.
 * Contact details use reserved example values (example.org, 555-01xx) that reach no one.
 */
import type { ContactChannel } from "./contact";

export interface DemoImage {
  readonly src: string;
  readonly webp: string;
  readonly alt: string;
}

const image = (name: string, alt = ""): DemoImage => ({
  src: `/demo/${name}.jpg`,
  webp: `/demo/${name}.webp`,
  alt,
});

export const demoImages = {
  hero: image("hero"),
  heroMobile: image("hero-mobile"),
  gathering: image("gathering", "Demo image: a congregation gathered under warm stage light"),
  page: image("page"),
  programs: [1, 2, 3, 4, 5, 6].map((n) => image(`program-0${n}`, "")),
  media: [1, 2, 3, 4].map((n) => image(`media-0${n}`, "")),
} as const;

/** Keyed by program name. */
export const demoProgramSchedule: Record<string, string> = {
  "Annual Retreat": "Demo date · January",
  "Mid-Year Retreat": "Demo date · June",
  "Sons of Oil Conference": "Demo date · August",
  "Singles Summit": "Demo date · February",
  "Global Altar Project": "Demo time · Every week, online",
  "Morphosis Encounter": "Demo date · October",
};

export interface DemoMediaItem {
  readonly title: string;
  readonly category: string;
  readonly meta: string;
}

export const demoMediaItems: readonly DemoMediaItem[] = [
  { title: "Transformation Precedes Manifestation", category: "Sermons", meta: "Demo · 48 min" },
  { title: "Worship Night: An Altar of Encounter", category: "Worship Sessions", meta: "Demo · 1 hr 12 min" },
  { title: "The Journey from Believer to Son", category: "Podcasts", meta: "Demo · Episode 01" },
  { title: "Sons of Oil: Impartation Session", category: "Conference Messages", meta: "Demo · 56 min" },
];

export const demoContactChannels: readonly ContactChannel[] = [
  { label: "Email (demo)", value: "hello@example.org", href: "mailto:hello@example.org" },
  { label: "Phone (demo)", value: "+1 555 010 0199", href: "tel:+15550100199" },
  { label: "Address (demo)", value: "Demo address, City, Country" },
];
